# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_uart/test_apps/rs485:
  disable:
    - if: SOC_UART_SUPPORTED != 1
    - if: IDF_TARGET in ["esp32c61"]
      temporary: true
      reason: IDF-9320 uart driver
  disable_test:
    - if: IDF_TARGET != "esp32"
      temporary: true
      reason: lack of runners
  depends_components:
    - esp_driver_uart
    - esp_driver_gpio

components/esp_driver_uart/test_apps/uart:
  disable:
    - if: SOC_UART_SUPPORTED != 1
    - if: IDF_TARGET in ["esp32c61"]
      temporary: true
      reason: IDF-9320 uart driver
  disable_test:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: test not pass, should be re-enable # TODO: IDF-8971
  depends_components:
    - esp_driver_uart
    - esp_driver_gpio

components/esp_driver_uart/test_apps/uart_vfs:
  depends_components:
    - esp_driver_uart
    - vfs
